<?php

/**
 * The admin-specific functionality of the plugin.
 *
 * @link       https://wpblockwriter.com
 * @since      1.0.0
 *
 * @package    Blockwriter
 * @subpackage Blockwriter/admin
 */
if ( ! defined( 'ABSPATH' ) ) exit;

/**
 * The admin-specific functionality of the plugin.
 *
 * Defines the plugin name, version, and two examples hooks for how to
 * enqueue the admin-specific stylesheet and JavaScript.
 *
 * @package    Blockwriter
 * @subpackage Blockwriter/admin
 * @author     Ri Themes <wpblockwriter@gmail.com>
 */
class Blockwriter_Admin
{

	/**
	 * The ID of this plugin.
	 *
	 * @since    1.0.0
	 * @access   private
	 * @var      string    $plugin_name    The ID of this plugin.
	 */
	private $plugin_name;

	/**
	 * The version of this plugin.
	 *
	 * @since    1.0.0
	 * @access   private
	 * @var      string    $version    The current version of this plugin.
	 */
	private $version;

	/**
	 * Initialize the class and set its properties.
	 *
	 * @since    1.0.0
	 * @param      string    $plugin_name       The name of this plugin.
	 * @param      string    $version    The version of this plugin.
	 */
	public function __construct($plugin_name, $version)
	{

		$this->plugin_name = $plugin_name;
		$this->version = $version;

	}

	/**
	 * Register the stylesheets for the admin area.
	 *
	 * @since    1.0.0
	 */
	public function enqueue_styles()
	{

		/**
		 * This function is provided for demonstration purposes only.
		 *
		 * An instance of this class should be passed to the run() function
		 * defined in Blockwriter_Loader as all of the hooks are defined
		 * in that particular class.
		 *
		 * The Blockwriter_Loader will then create the relationship
		 * between the defined hooks and the functions defined in this
		 * class.
		 */

		wp_enqueue_style('bootstrap', plugin_dir_url(__FILE__) . 'css/bootstrap.min.css', array(), '5.3.3', 'all');
    	wp_enqueue_style($this->plugin_name . '-editor', plugin_dir_url(__FILE__) . 'css/blockwriter-editor.css', array(), $this->version, 'all');
		wp_enqueue_style($this->plugin_name . '-admin', plugin_dir_url(__FILE__) . 'css/blockwriter-admin.css', array(), $this->version, 'all');

	}

	/**
	 * Register the JavaScript for the admin area.
	 *
	 * @since    1.0.0
	 */
	public function enqueue_scripts()
	{

		/**
		 * This function is provided for demonstration purposes only.
		 *
		 * An instance of this class should be passed to the run() function
		 * defined in Blockwriter_Loader as all of the hooks are defined
		 * in that particular class.
		 *
		 * The Blockwriter_Loader will then create the relationship
		 * between the defined hooks and the functions defined in this
		 * class.
		 */
		wp_enqueue_script('bootstrap-bundle', BLOCKWRITER_URL. 'public/js/bootstrap/bootstrap.bundle.min.js', array(), '5.3.3', 'all');
		wp_enqueue_script($this->plugin_name, plugin_dir_url(__FILE__) . 'js/blockwriter-admin.js', array('jquery'), $this->version, false);

	}

	/**
	 * Register the assets used inside the block editor.
	 *
	 * Loads the built pattern library bundle and its stylesheet only in the
	 * editor context. The asset file is generated by `wp-scripts` and provides
	 * the WordPress package dependencies and the content hash version.
	 *
	 * @since 1.0.4
	 */
	public function enqueue_editor_assets()
	{
		$asset_file = plugin_dir_path( __FILE__ ) . 'js/dist/admin.asset.php';

		if ( ! file_exists( $asset_file ) ) {
			return;
		}

		$asset = require $asset_file;

		$dependencies = isset( $asset['dependencies'] ) ? $asset['dependencies'] : array();
		$version      = isset( $asset['version'] ) ? $asset['version'] : $this->version;

		wp_enqueue_script(
			$this->plugin_name . '-editor',
			plugin_dir_url( __FILE__ ) . 'js/dist/admin.js',
			$dependencies,
			$version,
			true
		);

		$style_file = plugin_dir_path( __FILE__ ) . 'js/dist/admin.css';

		if ( file_exists( $style_file ) ) {
			wp_enqueue_style(
				$this->plugin_name . '-editor',
				plugin_dir_url( __FILE__ ) . 'js/dist/admin.css',
				array( 'wp-components' ),
				$version,
				'all'
			);
		}
	}
}
